version: 2.1
jobs:
  build: 
    working_directory: ~/repo

    docker: 
      - image: cimg/node:17.5.0

    steps:
      # Get code from git
      - checkout

      # Just let us know everything's ticking along
      - run: echo "yarn installing"

      # Restore our node_modules cache if we've run this before (likely!)
      - restore_cache:
          keys:
            - yarn-dependencies-{{checksum "yarn.lock"}}
            # If the above isn't found then there should be a general cache here
            - yarn-dependencies-

      # Make sure our dependencies are up to date
      - run: yarn install

      # Save the up to date cache for future runs
      - save_cache:
          paths:
            - .node_modules
          key: yarn-dependencies-{{checksum "yarn.lock"}}

      # Attempt to build the site
      - run:
          name: Build Gatsby Site
          command: CI=true yarn build

workflows:
  test_build:
    jobs:
      - build